package parsleyj.NetSecLab.lab1.prngcipher;

import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Scanner;

/**
 * Using a byte sequence input as seed, generates a pseudo-random sequence of bytes.
 * This sequence is used as key for a symmetric "xor" cipher.
 * <p>
 * Created on 28/02/2019.
 *
 * @author Giuseppe Petrosino - giuseppe.petrosino@studenti.unipr.it
 */
@SuppressWarnings("WeakerAccess")
public class PNRGStreamCipher {

    private byte[] key;

    /**
     * Initializes the cipher with a "key", which will be later used as seed to generate a pseudo-random sequence in
     * the encrypt and decrypt operations
     *
     * @param key the key
     */
    public PNRGStreamCipher(byte[] key) {
        this.key = key;
    }

    /**
     * Utility method to generate a String representation in hexadecimals of a byte array.
     *
     * @param buf the input array
     * @return a String containing the hexadecimal representation of buf
     */
    public static String toHexString(byte[] buf) {
        StringBuilder stringBuilder = new StringBuilder();
        //noinspection ForLoopReplaceableByForEach
        for (int i = 0; i < buf.length; i++) {
            stringBuilder
                    .append(Integer.toHexString((buf[i] >> 4) & 0x0f))
                    .append(Integer.toHexString(buf[i] & 0x0f));
        }
        return stringBuilder.toString();

    }

    public static 

    /**
     * Encrypts the given input byte sequence, using a random byte sequence generated by an instance of SecureRandom
     * (initialized with the SHA1PRNG algorithm) as key.
     * The seed of the SecureRandom instance is the byte sequence representation of the field {@link #key}.
     *
     * @param input the byte sequence
     * @return the encrypted byte sequence
     * @throws NoSuchAlgorithmException if the SHA1PRNG algorithm is not available in the environment
     */
    public byte[] encrypt(byte[] input) throws NoSuchAlgorithmException {
        byte[] seed = key.getBytes();
        SecureRandom secureRandom;

        secureRandom = SecureRandom.getInstance("SHA1PRNG");
        secureRandom.setSeed(seed);

        byte[] random = new byte[input.length];
        secureRandom.nextBytes(random);
        byte[] encriptedBytes = new byte[input.length];
        for (int i = 0; i < input.length; i++) {
            byte b1 = input[i];
            byte b2 = random[i];

            encriptedBytes[i] = (byte) (b1 ^ b2);
        }
        return encriptedBytes;
    }


    /**
     * Decrypts the given input byte sequence by calling internally the {@link #encrypt(byte[])} method. This is valid
     * design strategy due to the commutative property of the bit-wise xor operation.
     *
     * @param input the encrypted byte sequence
     * @return the decrypted byte sequence
     * @throws NoSuchAlgorithmException if the SHA1PRNG algorithm is not available in the environment
     */
    public byte[] decrypt(byte[] input) throws NoSuchAlgorithmException {
        return encrypt(input);
    }


    /**
     * An example entry point main method to test the cipher.
     *
     * @param argv COMMAND LINE ARGUMENTS IGNORED
     * @throws NoSuchAlgorithmException if the SHA1PRNG algorithm is not available in the environment
     */
    public static void main(String[] argv) throws NoSuchAlgorithmException {

        Scanner sc = new Scanner(System.in);

        System.out.println("Key = ?");
        String key = sc.nextLine();

        PNRGStreamCipher pnrgStreamCipher = new PNRGStreamCipher(key);

        System.out.println("Text = ?");
        String text = sc.nextLine();

        System.out.println();

        System.out.println("Text in hex:");
        System.out.println(toHexString(text.getBytes()));

        byte[] encrypted = pnrgStreamCipher.encrypt(text.getBytes());
        System.out.println("Encrypted (hex):");
        System.out.println(toHexString(encrypted));

        byte[] decrypted = pnrgStreamCipher.decrypt(encrypted);
        System.out.println("Decrypted (hex):");
        System.out.println(toHexString(decrypted));

        System.out.println("Decrypted text:");
        System.out.println(new String(decrypted));
    }
}
